import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// initmap is google buildin function it need to be declare in global 
declare global {
  interface Window {
    initMap: () => void;
  }
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <Script
        src={`https://maps.googleapis.com/maps/api/js?key=AIzaSyD-CWmVyAapUI5zhqL8zIj8Oa6a95UexVs&callback=initMap&libraries=places,drawing&v=weekly&v=weekly`}
        defer></Script>
      <Script src="https://polyfill.io/v3/polyfill.min.js?features=default"></Script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
